# Generated by Django 5.2.3 on 2025-10-27 05:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_project_options_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
