# Generated by Django 5.2.3 on 2025-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_profile_connections_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='connections',
        ),
        migrations.AddField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='chatters', to='Accounts.profile'),
        ),
    ]
