# Generated by Django 5.2.3 on 2025-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Connections', 'Connections'), ('Only me', 'Only me')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
