# Generated by Django 5.2.3 on 2025-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_profile_connections_profile_followers_and_more'),
        ('main', '0002_post_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('public', 'public'), ('connections', 'connections'), ('onlyme', 'onlyme')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='Accounts.profile'),
        ),
    ]
