# Generated by Django 5.2.3 on 2025-10-29 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_profile_connections_profile_chats'),
        ('main', '0003_notification_alter_post_audience_alter_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='notification',
            name='_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Comment', 'Comment'), ('Like', 'Like'), ('Info', 'Info')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='Accounts.profile'),
        ),
    ]
