# Generated by Django 5.2.3 on 2025-10-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notification_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='_type',
            new_name='type',
        ),
    ]
