# Generated by Django 5.2.3 on 2025-11-03 15:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_platform_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='courses'),
            preserve_default=False,
        ),
    ]
